package lab5_alessandroreyes;

import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.SpinnerNumberModel;
import javax.swing.tree.DefaultMutableTreeNode;
import javax.swing.tree.DefaultTreeModel;

public class PrincipalL extends javax.swing.JFrame {

    /**
     * Creates new form PrincipalL
     */
    public PrincipalL() {
        initComponents();
        //Licenciaturas-------------------------------------------------------------------------------------------
        Carrera c = new Carrera("Finanzas", "Licenciatura", 8000, "Clementina");
        carreras.add(c);
        c = new Carrera("Derecho", "Licenciatura", 8000, "Clementina");
        carreras.add(c);
        c = new Carrera("Administracion de Empresa", "Licenciatura", 8000, "Clementina");
        carreras.add(c);
        c = new Carrera("Diseño Grafico", "Licenciatura", 8500, "Clementina");
        carreras.add(c);
        c = new Carrera("Mercadoctenia", "Licenciatura", 8000, "Clementina");
        carreras.add(c);
        //Ingenieras------------------------------------------------------------------------------------------------
        c = new Carrera("Sistemas Computacionales", "Ingenieria", 9000, "Reynod");
        carreras.add(c);
        c = new Carrera("Industrial y de Sistemas", "Ingenieria", 9000, "Reynold");
        carreras.add(c);
        c = new Carrera("Mecatronica", "Ingenieria", 9000, "Reynold");
        carreras.add(c);
        c = new Carrera("Biomedica", "Ingenieria", 9000, "Reynold");
        carreras.add(c);
        c = new Carrera("Energia", "Ingenieria", 9000, "Reynold");
        carreras.add(c);
        //ciencias de la salud---------------------------------------------------------------------------------------
        c = new Carrera("Medicina y Cirugia", "Ciencias de la Salud", 15000, "Marlon");
        carreras.add(c);
        c = new Carrera("Odontologia", "Ciencias de la Salud", 11000, "Marlon");
        carreras.add(c);
        c = new Carrera("Nutricion", "Ciencias de la Salud", 9000, "Marlon");
        carreras.add(c);
        c = new Carrera("Terapia Fisica y Ocupacional", "Ciencias de la Salud", 9000, "Marlon");
        carreras.add(c);
        //Estudiantes-----------------------------------------------------------------------------------------------
        Estudiante es = new Estudiante("Alessandro", "Reyes", 11911224, 19, true, carreras.get(5));
        estudiantes.add(es);
        es = new Estudiante("Alvaro", "Reyes", 11611224, 24, true, carreras.get(5));
        estudiantes.add(es);
        es = new Estudiante("Daniel", "Trimarchi", 11711224, 20, true, carreras.get(5));
        estudiantes.add(es);
        es = new Estudiante("Adriana", "Parodi", 11811224, 19, false, carreras.get(10));
        estudiantes.add(es);
        //Clases---------------------------------------------------------------------------------------------------
        Clase cl = new Clase("Algebra", 2828, 5, 101, true);
        clases.add(cl);
        cl = new Clase("Microeconomia", 2804, 1, 201, false);
        clases.add(cl);
        cl = new Clase("Ecologia", 2078, 1, 301, false);
        clases.add(cl);
        //------------------------------------------------------------------------------------------------
        SpinnerNumberModel YY = new SpinnerNumberModel();
        YY.setMinimum(16);
        YY.setValue(16);
        js_estu_edad.setModel(YY);
        SpinnerNumberModel xx = new SpinnerNumberModel();
        xx.setMinimum(20);
        xx.setValue(20);
        js_crearM_edad.setModel(xx);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jd_crear_estudiante = new javax.swing.JDialog();
        btn_crearE_regresar = new javax.swing.JButton();
        btn_crear_estudiante = new javax.swing.JButton();
        tf_estudiante_nombre = new javax.swing.JTextField();
        tf_estudiante_apellido = new javax.swing.JTextField();
        tf_estudiante_cuenta = new javax.swing.JTextField();
        js_estu_edad = new javax.swing.JSpinner();
        cb_estu_carrera = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        rb_m = new javax.swing.JRadioButton();
        rb_f = new javax.swing.JRadioButton();
        bg_genero = new javax.swing.ButtonGroup();
        jd_listar_estudiantes = new javax.swing.JDialog();
        jScrollPane1 = new javax.swing.JScrollPane();
        jl_listar_estudiantes = new javax.swing.JList<>();
        btn_listarE_regresar = new javax.swing.JButton();
        jd_arbol = new javax.swing.JDialog();
        btn_arbol_regresar = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jt_estudiantes = new javax.swing.JTree();
        pop_op_estu = new javax.swing.JPopupMenu();
        pjmi_Agregar_arbol = new javax.swing.JMenuItem();
        pop_op_arbol = new javax.swing.JPopupMenu();
        pjmi_modE = new javax.swing.JMenuItem();
        pjmi_eliE = new javax.swing.JMenuItem();
        jd_mod_estu = new javax.swing.JDialog();
        btn_modE_regresar = new javax.swing.JButton();
        btn_modificarE = new javax.swing.JButton();
        tf_modE_nom = new javax.swing.JTextField();
        tf_modE_apellido = new javax.swing.JTextField();
        tf_modE_cuenta = new javax.swing.JTextField();
        js_mod_es = new javax.swing.JSpinner();
        rb_modE_m = new javax.swing.JRadioButton();
        rb_modE_f = new javax.swing.JRadioButton();
        cb_modE_carrera = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        bg_modE = new javax.swing.ButtonGroup();
        jd_crear_maestro = new javax.swing.JDialog();
        tf_crearM_nom = new javax.swing.JTextField();
        tf_crearM_apellido = new javax.swing.JTextField();
        tf_crearM_sala = new javax.swing.JTextField();
        js_crearM_edad = new javax.swing.JSpinner();
        jScrollPane3 = new javax.swing.JScrollPane();
        jl_crearM_clases = new javax.swing.JList<>();
        btn_crearM_r = new javax.swing.JButton();
        btn_crearM = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        jl_crearM_tiene = new javax.swing.JList<>();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        btn_addC = new javax.swing.JButton();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jd_crear_clase = new javax.swing.JDialog();
        jd_crear_carrera = new javax.swing.JDialog();
        tf_crearC_nom = new javax.swing.JTextField();
        tf_crearC_facu = new javax.swing.JTextField();
        tf_crearC_costo = new javax.swing.JTextField();
        tf_crearC_jefe = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        btn_crearC_regresar = new javax.swing.JButton();
        btn_crearC = new javax.swing.JButton();
        jd_listar_maestro = new javax.swing.JDialog();
        btn_listarM_r = new javax.swing.JButton();
        jScrollPane5 = new javax.swing.JScrollPane();
        jl_listarmaestros = new javax.swing.JList<>();
        jMenuBar1 = new javax.swing.JMenuBar();
        Acciones = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        jmi_crear_estudiantes = new javax.swing.JMenuItem();
        jmi_listar_estudiantes = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        jmi_crear_maestros = new javax.swing.JMenuItem();
        jmi_listar_maestros = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jmi_crear_carreras = new javax.swing.JMenuItem();
        jmi_listar_carreras = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jmi_crear_clases = new javax.swing.JMenuItem();
        jmi_listar_clases = new javax.swing.JMenuItem();
        jmi_arbol = new javax.swing.JMenuItem();

        btn_crearE_regresar.setText("Regresar");
        btn_crearE_regresar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_crearE_regresarMouseClicked(evt);
            }
        });

        btn_crear_estudiante.setText("Crear");
        btn_crear_estudiante.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_crear_estudianteMouseClicked(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel1.setText("Nombre");

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel2.setText("Apellido");

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel3.setText("Numero de cuenta");

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel4.setText("Edad");

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel5.setText("Genero");

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel6.setText("Carrera");

        bg_genero.add(rb_m);
        rb_m.setSelected(true);
        rb_m.setText("M");

        bg_genero.add(rb_f);
        rb_f.setText("F");

        javax.swing.GroupLayout jd_crear_estudianteLayout = new javax.swing.GroupLayout(jd_crear_estudiante.getContentPane());
        jd_crear_estudiante.getContentPane().setLayout(jd_crear_estudianteLayout);
        jd_crear_estudianteLayout.setHorizontalGroup(
            jd_crear_estudianteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jd_crear_estudianteLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btn_crearE_regresar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 119, Short.MAX_VALUE)
                .addGroup(jd_crear_estudianteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jd_crear_estudianteLayout.createSequentialGroup()
                        .addComponent(rb_m)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(rb_f))
                    .addGroup(jd_crear_estudianteLayout.createSequentialGroup()
                        .addComponent(cb_estu_carrera, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(240, 240, 240)
                        .addComponent(btn_crear_estudiante))
                    .addComponent(jLabel1)
                    .addComponent(jLabel3)
                    .addGroup(jd_crear_estudianteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(tf_estudiante_cuenta, javax.swing.GroupLayout.DEFAULT_SIZE, 349, Short.MAX_VALUE)
                        .addComponent(tf_estudiante_apellido)
                        .addComponent(tf_estudiante_nombre))
                    .addComponent(js_estu_edad, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jLabel2))
                .addContainerGap())
        );
        jd_crear_estudianteLayout.setVerticalGroup(
            jd_crear_estudianteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jd_crear_estudianteLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tf_estudiante_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tf_estudiante_apellido, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tf_estudiante_cuenta, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(js_estu_edad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jd_crear_estudianteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rb_m)
                    .addComponent(rb_f))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                .addGroup(jd_crear_estudianteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jd_crear_estudianteLayout.createSequentialGroup()
                        .addGroup(jd_crear_estudianteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btn_crearE_regresar)
                            .addComponent(btn_crear_estudiante))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jd_crear_estudianteLayout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cb_estu_carrera, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28))))
        );

        jl_listar_estudiantes.setModel(new DefaultListModel());
        jl_listar_estudiantes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jl_listar_estudiantesMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jl_listar_estudiantes);

        btn_listarE_regresar.setText("Regresar");
        btn_listarE_regresar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_listarE_regresarMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jd_listar_estudiantesLayout = new javax.swing.GroupLayout(jd_listar_estudiantes.getContentPane());
        jd_listar_estudiantes.getContentPane().setLayout(jd_listar_estudiantesLayout);
        jd_listar_estudiantesLayout.setHorizontalGroup(
            jd_listar_estudiantesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jd_listar_estudiantesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btn_listarE_regresar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 92, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 392, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(171, 171, 171))
        );
        jd_listar_estudiantesLayout.setVerticalGroup(
            jd_listar_estudiantesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jd_listar_estudiantesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jd_listar_estudiantesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jd_listar_estudiantesLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btn_listarE_regresar))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 493, Short.MAX_VALUE))
                .addContainerGap())
        );

        btn_arbol_regresar.setText("Regresar");
        btn_arbol_regresar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_arbol_regresarMouseClicked(evt);
            }
        });

        javax.swing.tree.DefaultMutableTreeNode treeNode1 = new javax.swing.tree.DefaultMutableTreeNode("Carreras");
        jt_estudiantes.setModel(new javax.swing.tree.DefaultTreeModel(treeNode1));
        jt_estudiantes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jt_estudiantesMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jt_estudiantes);

        javax.swing.GroupLayout jd_arbolLayout = new javax.swing.GroupLayout(jd_arbol.getContentPane());
        jd_arbol.getContentPane().setLayout(jd_arbolLayout);
        jd_arbolLayout.setHorizontalGroup(
            jd_arbolLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_arbolLayout.createSequentialGroup()
                .addGroup(jd_arbolLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jd_arbolLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btn_arbol_regresar))
                    .addGroup(jd_arbolLayout.createSequentialGroup()
                        .addGap(170, 170, 170)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 354, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(213, Short.MAX_VALUE))
        );
        jd_arbolLayout.setVerticalGroup(
            jd_arbolLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jd_arbolLayout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 384, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
                .addComponent(btn_arbol_regresar)
                .addContainerGap())
        );

        pjmi_Agregar_arbol.setText("Agregar al Arbol");
        pjmi_Agregar_arbol.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pjmi_Agregar_arbolActionPerformed(evt);
            }
        });
        pop_op_estu.add(pjmi_Agregar_arbol);

        pjmi_modE.setText("Modificar");
        pjmi_modE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pjmi_modEActionPerformed(evt);
            }
        });
        pop_op_arbol.add(pjmi_modE);

        pjmi_eliE.setText("Eliminar");
        pjmi_eliE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pjmi_eliEActionPerformed(evt);
            }
        });
        pop_op_arbol.add(pjmi_eliE);

        btn_modE_regresar.setText("Regresar");
        btn_modE_regresar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_modE_regresarMouseClicked(evt);
            }
        });

        btn_modificarE.setText("Modificar");
        btn_modificarE.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_modificarEMouseClicked(evt);
            }
        });

        bg_modE.add(rb_modE_m);
        rb_modE_m.setText("M");

        bg_modE.add(rb_modE_f);
        rb_modE_f.setText("F");

        jLabel7.setText("Nombre");

        jLabel8.setText("Apellido");

        jLabel9.setText("Numero de cuenta");

        jLabel10.setText("Edad");

        jLabel11.setText("Genero");

        jLabel12.setText("Carrera");

        javax.swing.GroupLayout jd_mod_estuLayout = new javax.swing.GroupLayout(jd_mod_estu.getContentPane());
        jd_mod_estu.getContentPane().setLayout(jd_mod_estuLayout);
        jd_mod_estuLayout.setHorizontalGroup(
            jd_mod_estuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_mod_estuLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btn_modE_regresar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_modificarE)
                .addContainerGap())
            .addGroup(jd_mod_estuLayout.createSequentialGroup()
                .addGap(185, 185, 185)
                .addGroup(jd_mod_estuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel12)
                    .addComponent(jLabel11)
                    .addComponent(jLabel10)
                    .addComponent(jLabel9)
                    .addComponent(jLabel8)
                    .addComponent(jLabel7)
                    .addGroup(jd_mod_estuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jd_mod_estuLayout.createSequentialGroup()
                            .addComponent(rb_modE_m)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(rb_modE_f))
                        .addComponent(tf_modE_nom, javax.swing.GroupLayout.DEFAULT_SIZE, 362, Short.MAX_VALUE)
                        .addComponent(tf_modE_apellido)
                        .addComponent(tf_modE_cuenta)
                        .addComponent(cb_modE_carrera, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(js_mod_es, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(203, Short.MAX_VALUE))
        );
        jd_mod_estuLayout.setVerticalGroup(
            jd_mod_estuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jd_mod_estuLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tf_modE_nom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tf_modE_apellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tf_modE_cuenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(js_mod_es, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jd_mod_estuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rb_modE_m)
                    .addComponent(rb_modE_f))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cb_modE_carrera, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addGroup(jd_mod_estuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_modE_regresar)
                    .addComponent(btn_modificarE))
                .addContainerGap())
        );

        jl_crearM_clases.setModel(new DefaultListModel());
        jScrollPane3.setViewportView(jl_crearM_clases);

        btn_crearM_r.setText("Regresar");
        btn_crearM_r.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_crearM_rMouseClicked(evt);
            }
        });

        btn_crearM.setText("Crear");
        btn_crearM.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_crearMMouseClicked(evt);
            }
        });

        jl_crearM_tiene.setModel(new DefaultListModel());
        jScrollPane4.setViewportView(jl_crearM_tiene);

        jLabel17.setText("Lista de clases existentes");

        jLabel18.setText("Clases que imparte el maestro");

        btn_addC.setText("Agregar clases al maestro");
        btn_addC.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_addCMouseClicked(evt);
            }
        });

        jLabel19.setText("Nombre");

        jLabel20.setText("Apellido");

        jLabel21.setText("Salario");

        jLabel22.setText("Edad");

        javax.swing.GroupLayout jd_crear_maestroLayout = new javax.swing.GroupLayout(jd_crear_maestro.getContentPane());
        jd_crear_maestro.getContentPane().setLayout(jd_crear_maestroLayout);
        jd_crear_maestroLayout.setHorizontalGroup(
            jd_crear_maestroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_crear_maestroLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jd_crear_maestroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jd_crear_maestroLayout.createSequentialGroup()
                        .addComponent(btn_crearM_r)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn_crearM))
                    .addGroup(jd_crear_maestroLayout.createSequentialGroup()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 56, Short.MAX_VALUE)
                        .addComponent(btn_addC)
                        .addGap(37, 37, 37)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jd_crear_maestroLayout.createSequentialGroup()
                        .addGroup(jd_crear_maestroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jd_crear_maestroLayout.createSequentialGroup()
                                .addGap(181, 181, 181)
                                .addGroup(jd_crear_maestroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jd_crear_maestroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(tf_crearM_sala, javax.swing.GroupLayout.DEFAULT_SIZE, 347, Short.MAX_VALUE)
                                        .addComponent(tf_crearM_apellido)
                                        .addComponent(tf_crearM_nom))
                                    .addComponent(js_crearM_edad, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel19)
                                    .addComponent(jLabel20)
                                    .addComponent(jLabel21)
                                    .addComponent(jLabel22)))
                            .addGroup(jd_crear_maestroLayout.createSequentialGroup()
                                .addComponent(jLabel17)
                                .addGap(366, 366, 366)
                                .addComponent(jLabel18)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jd_crear_maestroLayout.setVerticalGroup(
            jd_crear_maestroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_crear_maestroLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel19)
                .addGap(3, 3, 3)
                .addComponent(tf_crearM_nom, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addComponent(jLabel20)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tf_crearM_apellido, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16)
                .addComponent(jLabel21)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tf_crearM_sala, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22)
                .addComponent(jLabel22)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(js_crearM_edad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addGroup(jd_crear_maestroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(jLabel18))
                .addGroup(jd_crear_maestroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jd_crear_maestroLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jd_crear_maestroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 173, Short.MAX_VALUE)
                            .addComponent(jScrollPane3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jd_crear_maestroLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn_addC)
                        .addGap(113, 113, 113)))
                .addGroup(jd_crear_maestroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_crearM_r)
                    .addComponent(btn_crearM)))
        );

        javax.swing.GroupLayout jd_crear_claseLayout = new javax.swing.GroupLayout(jd_crear_clase.getContentPane());
        jd_crear_clase.getContentPane().setLayout(jd_crear_claseLayout);
        jd_crear_claseLayout.setHorizontalGroup(
            jd_crear_claseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jd_crear_claseLayout.setVerticalGroup(
            jd_crear_claseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        jLabel13.setText("Nombre de la carrera");

        jLabel14.setText("Facultad a la que pertenece");

        jLabel15.setText("Costo mensual");

        jLabel16.setText("Jefe de carrera");

        btn_crearC_regresar.setText("Regresar");

        btn_crearC.setText("Crear");

        javax.swing.GroupLayout jd_crear_carreraLayout = new javax.swing.GroupLayout(jd_crear_carrera.getContentPane());
        jd_crear_carrera.getContentPane().setLayout(jd_crear_carreraLayout);
        jd_crear_carreraLayout.setHorizontalGroup(
            jd_crear_carreraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_crear_carreraLayout.createSequentialGroup()
                .addGroup(jd_crear_carreraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jd_crear_carreraLayout.createSequentialGroup()
                        .addGap(213, 213, 213)
                        .addGroup(jd_crear_carreraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel16)
                            .addComponent(jLabel15)
                            .addComponent(jLabel14)
                            .addComponent(jLabel13)
                            .addComponent(tf_crearC_nom, javax.swing.GroupLayout.PREFERRED_SIZE, 316, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tf_crearC_costo, javax.swing.GroupLayout.PREFERRED_SIZE, 316, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tf_crearC_jefe, javax.swing.GroupLayout.PREFERRED_SIZE, 316, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tf_crearC_facu, javax.swing.GroupLayout.PREFERRED_SIZE, 316, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 212, Short.MAX_VALUE))
                    .addGroup(jd_crear_carreraLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btn_crearC_regresar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn_crearC)))
                .addContainerGap())
        );
        jd_crear_carreraLayout.setVerticalGroup(
            jd_crear_carreraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_crear_carreraLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tf_crearC_nom, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(56, 56, 56)
                .addComponent(jLabel14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tf_crearC_facu, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(60, 60, 60)
                .addComponent(jLabel15)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tf_crearC_costo, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(62, 62, 62)
                .addComponent(jLabel16)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tf_crearC_jefe, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 91, Short.MAX_VALUE)
                .addGroup(jd_crear_carreraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_crearC_regresar)
                    .addComponent(btn_crearC))
                .addContainerGap())
        );

        btn_listarM_r.setText("Regresar");
        btn_listarM_r.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_listarM_rMouseClicked(evt);
            }
        });

        jl_listarmaestros.setModel(new DefaultListModel());
        jScrollPane5.setViewportView(jl_listarmaestros);

        javax.swing.GroupLayout jd_listar_maestroLayout = new javax.swing.GroupLayout(jd_listar_maestro.getContentPane());
        jd_listar_maestro.getContentPane().setLayout(jd_listar_maestroLayout);
        jd_listar_maestroLayout.setHorizontalGroup(
            jd_listar_maestroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_listar_maestroLayout.createSequentialGroup()
                .addGroup(jd_listar_maestroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jd_listar_maestroLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btn_listarM_r))
                    .addGroup(jd_listar_maestroLayout.createSequentialGroup()
                        .addGap(199, 199, 199)
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 419, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(93, Short.MAX_VALUE))
        );
        jd_listar_maestroLayout.setVerticalGroup(
            jd_listar_maestroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jd_listar_maestroLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 402, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                .addComponent(btn_listarM_r)
                .addContainerGap())
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Acciones.setText("Acciones");

        jMenu3.setText("Estudiantes");

        jmi_crear_estudiantes.setText("Crear");
        jmi_crear_estudiantes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmi_crear_estudiantesActionPerformed(evt);
            }
        });
        jMenu3.add(jmi_crear_estudiantes);

        jmi_listar_estudiantes.setText("Listar");
        jmi_listar_estudiantes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmi_listar_estudiantesActionPerformed(evt);
            }
        });
        jMenu3.add(jmi_listar_estudiantes);

        Acciones.add(jMenu3);

        jMenu1.setText("Maestros");

        jmi_crear_maestros.setText("Crear");
        jmi_crear_maestros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmi_crear_maestrosActionPerformed(evt);
            }
        });
        jMenu1.add(jmi_crear_maestros);

        jmi_listar_maestros.setText("Listar");
        jmi_listar_maestros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmi_listar_maestrosActionPerformed(evt);
            }
        });
        jMenu1.add(jmi_listar_maestros);

        Acciones.add(jMenu1);

        jMenu2.setText("Carreras");

        jmi_crear_carreras.setText("Crear");
        jMenu2.add(jmi_crear_carreras);

        jmi_listar_carreras.setText("Listar");
        jMenu2.add(jmi_listar_carreras);

        Acciones.add(jMenu2);

        jMenu4.setText("Clases");

        jmi_crear_clases.setText("Crear");
        jMenu4.add(jmi_crear_clases);

        jmi_listar_clases.setText("Listar");
        jMenu4.add(jmi_listar_clases);

        Acciones.add(jMenu4);

        jmi_arbol.setText("Arbol");
        jmi_arbol.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmi_arbolActionPerformed(evt);
            }
        });
        Acciones.add(jmi_arbol);

        jMenuBar1.add(Acciones);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 739, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 491, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jmi_crear_estudiantesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmi_crear_estudiantesActionPerformed
        DefaultComboBoxModel modelo = new DefaultComboBoxModel(carreras.toArray());
        cb_estu_carrera.setModel(modelo);
        this.setVisible(false);
        jd_crear_estudiante.setModal(true);
        jd_crear_estudiante.pack();
        jd_crear_estudiante.setLocationRelativeTo(this);
        jd_crear_estudiante.setVisible(true);
    }//GEN-LAST:event_jmi_crear_estudiantesActionPerformed

    private void btn_crear_estudianteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_crear_estudianteMouseClicked
        boolean bandera = true;
        
        if(tf_estudiante_cuenta.getText() == null){
            JOptionPane.showMessageDialog(jd_crear_estudiante, "Tiene que ingresar un numero de cuenta.");
            bandera = false;
        }
        if(tf_estudiante_apellido.getText() == null){
            JOptionPane.showMessageDialog(jd_crear_estudiante, "Tiene que ingresar un apellido");
            bandera = false;
        }
        if(tf_estudiante_nombre.getText() == null){
            JOptionPane.showMessageDialog(jd_crear_estudiante, "Tiene que ingresar un nombre");
            bandera = false;
        }
        for (int i = 0; i < estudiantes.size(); i++) {
            if(Integer.parseInt(tf_estudiante_cuenta.getText()) == estudiantes.get(i).getCuenta()){
                JOptionPane.showMessageDialog(jd_crear_estudiante, "Error, el numero de cuenta ya esta asignado.");
                bandera = false;
                tf_estudiante_cuenta.setText("");
                break;
            }
        }
        boolean g = true;
        int x=0;
        if(bandera){
            for (int i = 0; i < carreras.size(); i++) {
                if(cb_estu_carrera.getSelectedItem().toString().equals(carreras.get(i).getNombre())){
                    x = i;
                    break;
                }
            }
            if(rb_m.isSelected()){
                g = true;
            } else {
                g = false;
            }
            Estudiante e = new Estudiante(tf_estudiante_nombre.getText(), tf_estudiante_apellido.getText(),
                    Integer.parseInt(tf_estudiante_cuenta.getText()), js_estu_edad.getComponentCount(),
                    g, carreras.get(x));
            estudiantes.add(e);
            JOptionPane.showMessageDialog(jd_crear_estudiante, "El estudiante fue creado con exito.");
            tf_estudiante_apellido.setText("");
            tf_estudiante_cuenta.setText("");
            tf_estudiante_nombre.setText("");
            cb_estu_carrera.setSelectedIndex(0);
            rb_m.setSelected(true);
            SpinnerNumberModel YY = new SpinnerNumberModel();
            YY.setMinimum(16);
            YY.setValue(16);
            js_estu_edad.setModel(YY);
        }
    }//GEN-LAST:event_btn_crear_estudianteMouseClicked

    private void btn_crearE_regresarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_crearE_regresarMouseClicked
        tf_estudiante_apellido.setText("");
        tf_estudiante_cuenta.setText("");
        tf_estudiante_nombre.setText("");
        cb_estu_carrera.setSelectedIndex(0);
        rb_m.setSelected(true);
        SpinnerNumberModel YY = new SpinnerNumberModel();
        YY.setMinimum(16);
        YY.setValue(16);
        js_estu_edad.setModel(YY);
        jd_crear_estudiante.setModal(false);
        jd_crear_estudiante.setVisible(false);
        this.setVisible(true);
        this.setLocationRelativeTo(this);
    }//GEN-LAST:event_btn_crearE_regresarMouseClicked

    private void jmi_listar_estudiantesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmi_listar_estudiantesActionPerformed
        DefaultListModel modeloLISTA = (DefaultListModel) jl_listar_estudiantes.getModel();
        
        for (int i = 0; i < estudiantes.size(); i++) {
            modeloLISTA.addElement(new Estudiante(estudiantes.get(i).getNombre(), estudiantes.get(i).getApellido(), 
            estudiantes.get(i).getCuenta(), estudiantes.get(i).getEdad(), estudiantes.get(i).isGenero(), estudiantes.get(i).getCarrera()));
        }
        jl_listar_estudiantes.setModel(modeloLISTA);
        this.setVisible(false);
        jd_listar_estudiantes.setModal(true);
        jd_listar_estudiantes.pack();
        jd_listar_estudiantes.setLocationRelativeTo(this);
        jd_listar_estudiantes.setVisible(true);
    }//GEN-LAST:event_jmi_listar_estudiantesActionPerformed

    private void btn_listarE_regresarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_listarE_regresarMouseClicked
        DefaultListModel modeloLISTA = (DefaultListModel) jl_listar_estudiantes.getModel();
        modeloLISTA.removeAllElements();
        jl_listar_estudiantes.setModel(modeloLISTA);
        
        jd_listar_estudiantes.setModal(false);
        jd_listar_estudiantes.setVisible(false);
        
        this.setVisible(true);
        this.setLocationRelativeTo(this);
    }//GEN-LAST:event_btn_listarE_regresarMouseClicked

    private void jl_listar_estudiantesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jl_listar_estudiantesMouseClicked
        if (jl_listar_estudiantes.getSelectedIndex() >= 0) {
            if (evt.isMetaDown()) {
                pop_op_estu.show(evt.getComponent(), evt.getX(), evt.getY());
            }
        }
    }//GEN-LAST:event_jl_listar_estudiantesMouseClicked

    private void pjmi_Agregar_arbolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pjmi_Agregar_arbolActionPerformed
        if (jl_listar_estudiantes.getSelectedIndex() >= 0) {
            DefaultTreeModel modeloARBOL = (DefaultTreeModel) jt_estudiantes.getModel();
            DefaultMutableTreeNode raiz
                    = (DefaultMutableTreeNode) modeloARBOL.getRoot();
            //obtener la persona a guardar
            DefaultListModel modeloLISTA
                    = (DefaultListModel) jl_listar_estudiantes.getModel();
            String nombre, apellido;
            int cuenta, edad;
            boolean gene;
            Carrera ca;
            nombre = ((Estudiante) modeloLISTA.get(
                    jl_listar_estudiantes.getSelectedIndex())).getNombre();
            apellido = ((Estudiante) modeloLISTA.get(
                    jl_listar_estudiantes.getSelectedIndex())).getApellido();
            cuenta = ((Estudiante) modeloLISTA.get(
                    jl_listar_estudiantes.getSelectedIndex())).getEdad();
            edad = ((Estudiante) modeloLISTA.get(
                    jl_listar_estudiantes.getSelectedIndex())).getCuenta();
            gene = ((Estudiante) modeloLISTA.get(
                    jl_listar_estudiantes.getSelectedIndex())).isGenero();
            ca = ((Estudiante) modeloLISTA.get(
                    jl_listar_estudiantes.getSelectedIndex())).getCarrera();
            int centinela = -1;
            boolean a = false;
            for (int i = 0; i < raiz.getChildCount(); i++) {
                if (raiz.getChildAt(i).toString().equals(ca.getNombre())) {
                    for (int j = 0; j < raiz.getChildAt(i).getChildCount(); j++) {
                        if (raiz.getChildAt(i).getChildAt(j).toString().equals(nombre)) {
                            a = true;
                            JOptionPane.showMessageDialog(this, "la persona ya existe");
                            break;
                        } else if (j == raiz.getChildAt(i).getChildCount()-1
                                && !raiz.getChildAt(i).getChildAt(j).toString().equals(nombre)) {
                            a = true;
                            DefaultMutableTreeNode p
                                    = new DefaultMutableTreeNode(
                                            new Estudiante(nombre, apellido, cuenta, edad, gene, ca));
                            ((DefaultMutableTreeNode) raiz.getChildAt(i)).add(p);
                            break;
                        }//fin del elseif
                    }//fin del for2
                    if (a == true) {
                        centinela = 1;
                    }
                }//fin if
            }//fin for1
            if (centinela == -1) {
                DefaultMutableTreeNode n
                        = new DefaultMutableTreeNode(ca.getNombre());
                DefaultMutableTreeNode p
                        = new DefaultMutableTreeNode(
                                new Estudiante(nombre, apellido, cuenta, edad, gene, ca));
                n.add(p);
                raiz.add(n);
            }//fin if
            modeloARBOL.reload();
        } else {
            JOptionPane.showMessageDialog(this, "No hay persona seleccionada");
        }
    }//GEN-LAST:event_pjmi_Agregar_arbolActionPerformed

    private void jmi_arbolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmi_arbolActionPerformed
        this.setVisible(false);
        jd_arbol.setModal(true);
        jd_arbol.pack();
        jd_arbol.setLocationRelativeTo(this);
        jd_arbol.setVisible(true);
    }//GEN-LAST:event_jmi_arbolActionPerformed

    private void btn_arbol_regresarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_arbol_regresarMouseClicked
        jd_arbol.setModal(false);
        jd_arbol.setVisible(false);
        
        this.setVisible(true);
        this.setLocationRelativeTo(this);
    }//GEN-LAST:event_btn_arbol_regresarMouseClicked

    private void jt_estudiantesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jt_estudiantesMouseClicked
        if(evt.isMetaDown()){
            int row = jt_estudiantes.getClosestRowForLocation(evt.getX(), evt.getY());
            jt_estudiantes.setSelectionRow(row);
             v1=
                    jt_estudiantes.getSelectionPath().getLastPathComponent();
            nodo_seleccionado = (DefaultMutableTreeNode) v1;
            if(nodo_seleccionado.getUserObject() instanceof Estudiante){
                estudiante_seleccionado
                        = (Estudiante) nodo_seleccionado.getUserObject();
                pop_op_arbol.show(evt.getComponent(), evt.getX(), evt.getY());
                
            }
        }
    }//GEN-LAST:event_jt_estudiantesMouseClicked

    private void pjmi_eliEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pjmi_eliEActionPerformed
        int response = JOptionPane.showConfirmDialog(this, "Seguro de Eliminarlo?", "Confirm", 
                JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
        if(response == JOptionPane.OK_OPTION){
            DefaultTreeModel m = (DefaultTreeModel) jt_estudiantes.getModel();
            m.removeNodeFromParent(nodo_seleccionado);
            m.reload();
            for (int i = 0; i < estudiantes.size(); i++) {
                if(estudiante_seleccionado.getNombre().equals(estudiantes.get(i).getNombre())){
                    estudiantes.remove(i);
                    break;
                }
            }
        }
    }//GEN-LAST:event_pjmi_eliEActionPerformed

    private void pjmi_modEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pjmi_modEActionPerformed
        tf_modE_nom.setText(estudiante_seleccionado.getNombre());
        tf_modE_apellido.setText(estudiante_seleccionado.getApellido());
        tf_modE_cuenta.setText(Integer.toString(estudiante_seleccionado.getEdad()));
        SpinnerNumberModel YY = new SpinnerNumberModel();
        YY.setMinimum(16);
        YY.setValue(estudiante_seleccionado.getCuenta());
        js_mod_es.setModel(YY);
        if(estudiante_seleccionado.isGenero() == true){
            rb_modE_m.setSelected(true);
        }else{
            rb_modE_f.setSelected(true);
        }
        DefaultComboBoxModel modelo = new DefaultComboBoxModel(carreras.toArray());
        cb_modE_carrera.setModel(modelo);
        int x=0;
        for (int i = 0; i < carreras.size(); i++) {
            if(estudiante_seleccionado.getCarrera().getNombre().equals(carreras.get(i).getNombre())){
                x=i;
            }
        }
        cb_modE_carrera.setSelectedIndex(x);
        jd_arbol.setModal(false);
        jd_arbol.setVisible(false);
        jd_mod_estu.setModal(true);
        jd_mod_estu.pack();
        jd_mod_estu.setLocationRelativeTo(this);
        jd_mod_estu.setVisible(true);
    }//GEN-LAST:event_pjmi_modEActionPerformed

    private void btn_modE_regresarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_modE_regresarMouseClicked
        jd_mod_estu.setModal(false);
        jd_mod_estu.setVisible(false);
        jd_arbol.setModal(true);
        jd_arbol.pack();
        jd_arbol.setLocationRelativeTo(this);
        jd_arbol.setVisible(true);
    }//GEN-LAST:event_btn_modE_regresarMouseClicked

    private void btn_modificarEMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_modificarEMouseClicked
        boolean bandera = true;
        Estudiante temp = (Estudiante) estudiante_seleccionado;
        int y = 0;
        for (int i = 0; i < estudiantes.size(); i++) {
            if (temp.getCuenta() == estudiantes.get(i).getCuenta()) {
                y = i;
            }
        }
        if (tf_modE_cuenta.getText() == null) {
            JOptionPane.showMessageDialog(jd_mod_estu, "Tiene que ingresar un numero de cuenta.");
            bandera = false;
        }
        if (tf_modE_apellido.getText() == null){
            JOptionPane.showMessageDialog(jd_mod_estu, "Tiene que ingresar un apellido");
            bandera = false;
        }
        if(tf_modE_nom.getText() == null){
            JOptionPane.showMessageDialog(jd_mod_estu, "Tiene que ingresar un nombre");
            bandera = false;
        }
        for (int i = 0; i < estudiantes.size(); i++) {
            if (Integer.parseInt(tf_modE_cuenta.getText()) == estudiantes.get(i).getCuenta()) {
                if (y != i) {
                    JOptionPane.showMessageDialog(jd_mod_estu, "Error, el numero de cuenta ya esta asignado.");
                    bandera = false;
                    tf_modE_cuenta.setText("");
                    break;
                }
            }
        }
        boolean g = true;
        int x=0;
        if(bandera){
            for (int i = 0; i < carreras.size(); i++) {
                if(cb_modE_carrera.getSelectedItem().toString().equals(carreras.get(i).getNombre())){
                    x = i;
                    break;
                }
            }
            if(rb_m.isSelected()){
                g = true;
            } else {
                g = false;
            }
            
            estudiantes.get(y).setNombre(tf_modE_nom.getText());
            estudiantes.get(y).setApellido(tf_modE_apellido.getText());
            estudiantes.get(y).setCuenta(Integer.parseInt(tf_modE_cuenta.getText()));
            estudiantes.get(y).setEdad(js_mod_es.getComponentCount());
            estudiantes.get(y).setGenero(g);
            estudiantes.get(y).setCarrera(carreras.get(x));
//            estudiante_seleccionado.setNombre(tf_modE_nom.getText());
//            estudiante_seleccionado.setApellido(tf_modE_apellido.getText());
//            estudiante_seleccionado.setCuenta(Integer.parseInt(tf_modE_cuenta.getText()));
//            estudiante_seleccionado.setEdad(js_mod_es.getComponentCount());
//            estudiante_seleccionado.setGenero(g);
//            estudiante_seleccionado.setCarrera(carreras.get(x));
//            nodo_seleccionado.setUserObject( estudiante_seleccionado);
//            v1=
//                    jt_estudiantes.getSelectionPath().getLastPathComponent();
//            nodo_seleccionado = (DefaultMutableTreeNode) estudiante_seleccionado;
//            DefaultTreeModel m = (DefaultTreeModel) jt_estudiantes.getModel();
//            m.removeNodeFromParent(nodo_seleccionado);
//            m.insertNodeInto(nodo_seleccionado, nodo_seleccionado, v1);
//            m.reload();
            
            JOptionPane.showMessageDialog(jd_mod_estu, "El estudiante fue modificado con exito");
            jd_mod_estu.setModal(false);
            jd_mod_estu.setVisible(false);
            jd_arbol.setModal(true);
            jd_arbol.pack();
            jd_arbol.setLocationRelativeTo(this);
            jd_arbol.setVisible(true);
        }
    }//GEN-LAST:event_btn_modificarEMouseClicked

    private void jmi_crear_maestrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmi_crear_maestrosActionPerformed
        DefaultListModel modeloLISTA = (DefaultListModel) jl_crearM_clases.getModel();
        
        for (int i = 0; i < clases.size(); i++) {
            modeloLISTA.addElement(new Clase(clases.get(i).getNombre(), clases.get(i).getSeccion(),
             clases.get(i).getEdificio(), clases.get(i).getSalon(), clases.get(i).isAire()));
        }
        jl_crearM_clases.setModel(modeloLISTA);
        
        this.setVisible(false);
        jd_crear_maestro.setModal(true);
        jd_crear_maestro.pack();
        jd_crear_maestro.setLocationRelativeTo(this);
        jd_crear_maestro.setVisible(true);
    }//GEN-LAST:event_jmi_crear_maestrosActionPerformed

    private void btn_crearM_rMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_crearM_rMouseClicked
        DefaultListModel modeloLISTA = (DefaultListModel) jl_crearM_clases.getModel();
        modeloLISTA.removeAllElements();
        jl_crearM_clases.setModel(modeloLISTA);
        tf_crearM_apellido.setText("");
        tf_crearM_nom.setText("");
        tf_crearM_sala.setText("");
        SpinnerNumberModel xx = new SpinnerNumberModel();
        xx.setMinimum(20);
        xx.setValue(20);
        js_crearM_edad.setModel(xx);
        DefaultListModel modeloLISTA2 = (DefaultListModel) jl_crearM_tiene.getModel();
        modeloLISTA2.removeAllElements();
        jl_crearM_tiene.setModel(modeloLISTA2);
        jd_crear_maestro.setModal(false);
        jd_crear_maestro.setVisible(false);
        this.setVisible(true);
        this.setLocationRelativeTo(this);
    }//GEN-LAST:event_btn_crearM_rMouseClicked

    private void btn_addCMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_addCMouseClicked
        if (jl_crearM_clases.getSelectedIndex() >= 0) {
            DefaultListModel modeloLISTA = (DefaultListModel) jl_crearM_clases.getModel();
            DefaultListModel modeloLISTA2 = (DefaultListModel) jl_crearM_tiene.getModel();
            modeloLISTA2.addElement(new Clase(((Clase) modeloLISTA.get(
                    jl_crearM_clases.getSelectedIndex())).getNombre(), ((Clase) modeloLISTA.get(
                    jl_crearM_clases.getSelectedIndex())).getSeccion(), ((Clase) modeloLISTA.get(
                    jl_crearM_clases.getSelectedIndex())).getEdificio(), ((Clase) modeloLISTA.get(
                    jl_crearM_clases.getSelectedIndex())).getSalon(), ((Clase) modeloLISTA.get(
                    jl_crearM_clases.getSelectedIndex())).isAire()));
            jl_crearM_tiene.setModel(modeloLISTA2);
        }
    }//GEN-LAST:event_btn_addCMouseClicked

    private void btn_crearMMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_crearMMouseClicked
        boolean bandera = true;
        if(tf_crearM_apellido.getText() == null){
            JOptionPane.showMessageDialog(jd_crear_maestro, "Tiene que ingresar un apellido");
            bandera =false;
        }
        if(tf_crearM_sala.getText() == null){
            JOptionPane.showMessageDialog(jd_crear_maestro, "Tiene que ingresar un Salario");
            bandera =false;
        }
        if(tf_crearM_nom.getText() == null){
            JOptionPane.showMessageDialog(jd_crear_maestro, "Tiene que ingresar un Nombre");
            bandera =false;
        }
        if(bandera){
            try {
                Maestro m = new Maestro(tf_crearM_nom.getText(), tf_crearM_apellido.getText(),
                        Integer.parseInt(tf_crearM_sala.getText()), js_mod_es.getComponentCount());
                maestros.add(m);
                JOptionPane.showMessageDialog(jd_crear_maestro, "Maestro creado con exito");
                tf_crearM_apellido.setText("");
                tf_crearM_nom.setText("");
                tf_crearM_sala.setText("");
                SpinnerNumberModel xx = new SpinnerNumberModel();
                xx.setMinimum(20);
                xx.setValue(20);
                js_crearM_edad.setModel(xx);
                DefaultListModel modeloLISTA2 = (DefaultListModel) jl_crearM_tiene.getModel();
                modeloLISTA2.removeAllElements();
                jl_crearM_tiene.setModel(modeloLISTA2);
            } catch (Exception e) {
            }
        }
    }//GEN-LAST:event_btn_crearMMouseClicked

    private void jmi_listar_maestrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmi_listar_maestrosActionPerformed
        DefaultListModel modeloLISTA = (DefaultListModel) jl_listarmaestros.getModel();
        
        for (int i = 0; i < maestros.size(); i++) {
            modeloLISTA.addElement(new Maestro(maestros.get(i).getNombre(), maestros.get(i).getApellido(),
             maestros.get(i).getSalario(), maestros.get(i).getEdad()));
        }
        jl_listarmaestros.setModel(modeloLISTA);
        this.setVisible(false);
        jd_listar_maestro.setModal(true);
        jd_listar_maestro.pack();
        jd_listar_maestro.setLocationRelativeTo(this);
        jd_listar_maestro.setVisible(true);
    }//GEN-LAST:event_jmi_listar_maestrosActionPerformed

    private void btn_listarM_rMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_listarM_rMouseClicked
        DefaultListModel modeloLISTA = (DefaultListModel) jl_listarmaestros.getModel();
        modeloLISTA.removeAllElements();
        jl_listarmaestros.setModel(modeloLISTA);
        jd_listar_maestro.setVisible(false);
        jd_listar_maestro.setModal(false);
        this.setVisible(true);
    }//GEN-LAST:event_btn_listarM_rMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PrincipalL.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PrincipalL.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PrincipalL.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PrincipalL.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PrincipalL().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu Acciones;
    private javax.swing.ButtonGroup bg_genero;
    private javax.swing.ButtonGroup bg_modE;
    private javax.swing.JButton btn_addC;
    private javax.swing.JButton btn_arbol_regresar;
    private javax.swing.JButton btn_crearC;
    private javax.swing.JButton btn_crearC_regresar;
    private javax.swing.JButton btn_crearE_regresar;
    private javax.swing.JButton btn_crearM;
    private javax.swing.JButton btn_crearM_r;
    private javax.swing.JButton btn_crear_estudiante;
    private javax.swing.JButton btn_listarE_regresar;
    private javax.swing.JButton btn_listarM_r;
    private javax.swing.JButton btn_modE_regresar;
    private javax.swing.JButton btn_modificarE;
    private javax.swing.JComboBox<String> cb_estu_carrera;
    private javax.swing.JComboBox<String> cb_modE_carrera;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JDialog jd_arbol;
    private javax.swing.JDialog jd_crear_carrera;
    private javax.swing.JDialog jd_crear_clase;
    private javax.swing.JDialog jd_crear_estudiante;
    private javax.swing.JDialog jd_crear_maestro;
    private javax.swing.JDialog jd_listar_estudiantes;
    private javax.swing.JDialog jd_listar_maestro;
    private javax.swing.JDialog jd_mod_estu;
    private javax.swing.JList<String> jl_crearM_clases;
    private javax.swing.JList<String> jl_crearM_tiene;
    private javax.swing.JList<String> jl_listar_estudiantes;
    private javax.swing.JList<String> jl_listarmaestros;
    private javax.swing.JMenuItem jmi_arbol;
    private javax.swing.JMenuItem jmi_crear_carreras;
    private javax.swing.JMenuItem jmi_crear_clases;
    private javax.swing.JMenuItem jmi_crear_estudiantes;
    private javax.swing.JMenuItem jmi_crear_maestros;
    private javax.swing.JMenuItem jmi_listar_carreras;
    private javax.swing.JMenuItem jmi_listar_clases;
    private javax.swing.JMenuItem jmi_listar_estudiantes;
    private javax.swing.JMenuItem jmi_listar_maestros;
    private javax.swing.JSpinner js_crearM_edad;
    private javax.swing.JSpinner js_estu_edad;
    private javax.swing.JSpinner js_mod_es;
    private javax.swing.JTree jt_estudiantes;
    private javax.swing.JMenuItem pjmi_Agregar_arbol;
    private javax.swing.JMenuItem pjmi_eliE;
    private javax.swing.JMenuItem pjmi_modE;
    private javax.swing.JPopupMenu pop_op_arbol;
    private javax.swing.JPopupMenu pop_op_estu;
    private javax.swing.JRadioButton rb_f;
    private javax.swing.JRadioButton rb_m;
    private javax.swing.JRadioButton rb_modE_f;
    private javax.swing.JRadioButton rb_modE_m;
    private javax.swing.JTextField tf_crearC_costo;
    private javax.swing.JTextField tf_crearC_facu;
    private javax.swing.JTextField tf_crearC_jefe;
    private javax.swing.JTextField tf_crearC_nom;
    private javax.swing.JTextField tf_crearM_apellido;
    private javax.swing.JTextField tf_crearM_nom;
    private javax.swing.JTextField tf_crearM_sala;
    private javax.swing.JTextField tf_estudiante_apellido;
    private javax.swing.JTextField tf_estudiante_cuenta;
    private javax.swing.JTextField tf_estudiante_nombre;
    private javax.swing.JTextField tf_modE_apellido;
    private javax.swing.JTextField tf_modE_cuenta;
    private javax.swing.JTextField tf_modE_nom;
    // End of variables declaration//GEN-END:variables
    private ArrayList <Estudiante> estudiantes = new ArrayList();
    private ArrayList <Carrera> carreras = new ArrayList();
    private ArrayList <Maestro> maestros = new ArrayList();
    private ArrayList <Clase> clases = new ArrayList();
    DefaultMutableTreeNode nodo_seleccionado;
    Estudiante estudiante_seleccionado;
    Object v1;
}
